version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_DATABASE: shibakita
      MYSQL_USER: toshiro
      MYSQL_PASSWORD: /run/secrets/mysql_password
    ports:
      - "3306:3306"
    networks:
      - mysql_network
    volumes:
      - mysql_data:/var/lib/mysql
    configs:
      - source: mysql_config
        target: /etc/mysql/conf.d/my.cnf
    secrets:
      - mysql_root_password
      - mysql_password

configs:
  mysql_config:
    file: ./my.cnf

secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true

networks:
  mysql_network:
    driver: overlay

volumes:
  mysql_data:
    driver: local
