version: '3.8'

services:
  nginx_lb:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

configs:
  nginx_config:
    content: |
      upstream php_backend {
        server php1:8081;
        server php2:8081;
        server php3:8081;
      }
      
      server {
        listen 80;
        server_name localhost;
        
        location / {
          proxy_pass http://php_backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

networks:
  default:
    external: true
    name: app_network